### ISSUE TITLE
CSS Fixes 

### ISSUE THREAD

**Issue by lloan** [ledkyb/studio#21]
- Borders on buttons - buttons should not have any borders per design. -> https://i.imgur.com/zL4y4r9.png 
- User images are squashed - currently not square ratio. They're 125px x 100px - make sure they're square - either 125x125 or 100x100. -> https://i.imgur.com/cQo2Td3.png 
- On mobile, blog section has a white space on left. -> https://i.imgur.com/gm1LK1l.png 
- Incorrect background color for arrow container -> https://i.imgur.com/zHxSapA.png (double check - not sure)
- Services section on mobile - clouds are broken -> https://i.imgur.com/6KoDg8e.png 
- Contact form - minor enhancements -> https://i.imgur.com/FsERjgT.png  minor alingment issues, design -> https://i.imgur.com/voidzNR.png 
- Blog height is too big -> https://i.imgur.com/bkbAV3E.jpg

**Comment by VelazquezLuis** [comment]
will tackle blog issues today, does anyone have the link to direct to the colors agreed on,  @lloan  at what width size did those borders appear?

**Comment by amacbain1** [comment]
@VelazquezLuis The colors are in the index.scss file

**Comment by amyFEND** [comment]
I’m working on the buttons. I think the borders in question are when you hover over the buttons.

**Comment by lloan** [comment]
It’s the rest state of Buttons on mobile. They had a black border.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by VelazquezLuis** [comment]
seem to have fixed blog issues, hopefully just made the pull request
