### ISSUE TITLE
Hamburger Icon vanishes

### ISSUE THREAD

**Issue by VelazquezLuis** [ledkyb/studio#42]
Hamburger Icon vanishes(blends in) when contrasted against orange background. 
![image](https://user-images.githubusercontent.com/35620778/51157526-dbbe4280-1845-11e9-87c5-55f6db33a71c.png)

**Comment by tonynguyen111997** [comment]
I think @amyFEND fixed this issue in her "uifixes" branch.

**Comment by amyFEND** [comment]
Hamburger icon changes color as expected on uifixes branch.

**Comment by amyFEND** [comment]
Hamburger icon and logo icon issue has been addressed. Closing issue.
